### ISSUE TITLE
Add more PR requirements checklist items

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#920]
**Is your feature request related to a problem? Please describe.**
When contributors create new PRs, it is sometimes challenging to know that the PR full fills all the requirements since the current checklist items do not cover all the requirements for a PR to be merged.

**Describe the solution you'd like**
We would like for the Pull request template to include the 4 checklist items below:
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes #ISSUE-NUMBER" or "Fixes #ISSUE-NUMBER" in the description to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) and automatically close it.
* [ ] I've updated corresponding documentation for the changes in this PR.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.

**Describe alternatives you've considered**
Always asking contributors about the status of a PR in the comments. This is tiresome

**Additional context**
- [Here](https://github.com/airqo-platform/AirQo-frontend/blob/staging/.github/PULL_REQUEST_TEMPLATE.md) is the PR template file
- The section to update:
  https://github.com/airqo-platform/AirQo-frontend/blob/4076924ebe955785898ceae0861a69bc8c758c1b/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L8

**Comment by HassanBahati** [comment]
@123MwanjeMike does this mean we are getting rid of the current check list under status of maturity and replacing it with the checklist in the description?

is this all meant to be removed and replaced by the checklist in the description
![Screenshot from 2022-11-10 07-31-37](https://user-images.githubusercontent.com/65954740/201001364-6e2507a3-94eb-47ac-a4bc-348135f16319.png)

**Comment by 123MwanjeMike** [comment]
Not really @HassanBahati 
We’re just adding new ones

**Comment by HassanBahati** [comment]
> Not really @HassanBahati We’re just adding new ones onto the already existing ones

okay then , will maintain the current and add the new ones
